# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/duyliontran/xilinx/zturn-driver/zturn-driver.srcs/sources_1/bd/zturn/ip/zturn_pnq_0_1/zturn_pnq_0_1.xci
# IP: The module: 'zturn_pnq_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/duyliontran/xilinx/zturn-driver/zturn-driver.gen/sources_1/bd/zturn/ip/zturn_pnq_0_1/constraints/pnq_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zturn_pnq_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/duyliontran/xilinx/zturn-driver/zturn-driver.srcs/sources_1/bd/zturn/ip/zturn_pnq_0_1/zturn_pnq_0_1.xci
# IP: The module: 'zturn_pnq_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/duyliontran/xilinx/zturn-driver/zturn-driver.gen/sources_1/bd/zturn/ip/zturn_pnq_0_1/constraints/pnq_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zturn_pnq_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
