# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/duyliontran/xilinx/zturn-driver/zturn-driver.srcs/sources_1/bd/zturn/ip/zturn_axi_intc_0_0/zturn_axi_intc_0_0.xci
# IP: The module: 'zturn_axi_intc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/duyliontran/xilinx/zturn-driver/zturn-driver.gen/sources_1/bd/zturn/ip/zturn_axi_intc_0_0/zturn_axi_intc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zturn_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/duyliontran/xilinx/zturn-driver/zturn-driver.gen/sources_1/bd/zturn/ip/zturn_axi_intc_0_0/zturn_axi_intc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zturn_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/duyliontran/xilinx/zturn-driver/zturn-driver.gen/sources_1/bd/zturn/ip/zturn_axi_intc_0_0/zturn_axi_intc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zturn_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/duyliontran/xilinx/zturn-driver/zturn-driver.srcs/sources_1/bd/zturn/ip/zturn_axi_intc_0_0/zturn_axi_intc_0_0.xci
# IP: The module: 'zturn_axi_intc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/duyliontran/xilinx/zturn-driver/zturn-driver.gen/sources_1/bd/zturn/ip/zturn_axi_intc_0_0/zturn_axi_intc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zturn_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/duyliontran/xilinx/zturn-driver/zturn-driver.gen/sources_1/bd/zturn/ip/zturn_axi_intc_0_0/zturn_axi_intc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zturn_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/duyliontran/xilinx/zturn-driver/zturn-driver.gen/sources_1/bd/zturn/ip/zturn_axi_intc_0_0/zturn_axi_intc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zturn_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
