# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/vdma_hdmi.xdc

# Block Designs: bd/zturn/zturn.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zturn || ORIG_REF_NAME==zturn} -quiet] -quiet

# IP: bd/zturn/ip/zturn_axi_intc_0_0/zturn_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zturn_axi_intc_0_0 || ORIG_REF_NAME==zturn_axi_intc_0_0} -quiet] -quiet

# IP: bd/zturn/ip/zturn_processing_system7_0_0/zturn_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zturn_processing_system7_0_0 || ORIG_REF_NAME==zturn_processing_system7_0_0} -quiet] -quiet

# IP: bd/zturn/ip/zturn_xbar_0/zturn_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zturn_xbar_0 || ORIG_REF_NAME==zturn_xbar_0} -quiet] -quiet

# IP: bd/zturn/ip/zturn_ps7_0_axi_periph_0/zturn_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zturn_ps7_0_axi_periph_0 || ORIG_REF_NAME==zturn_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zturn/ip/zturn_rst_ps7_0_145M_0/zturn_rst_ps7_0_145M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zturn_rst_ps7_0_145M_0 || ORIG_REF_NAME==zturn_rst_ps7_0_145M_0} -quiet] -quiet

# IP: bd/zturn/ip/zturn_xlconstant_0_0/zturn_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zturn_xlconstant_0_0 || ORIG_REF_NAME==zturn_xlconstant_0_0} -quiet] -quiet

# IP: bd/zturn/ip/zturn_xlconcat_0_0/zturn_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zturn_xlconcat_0_0 || ORIG_REF_NAME==zturn_xlconcat_0_0} -quiet] -quiet

# IP: bd/zturn/ip/zturn_pnq_0_1/zturn_pnq_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zturn_pnq_0_1 || ORIG_REF_NAME==zturn_pnq_0_1} -quiet] -quiet

# IP: bd/zturn/ip/zturn_auto_pc_0/zturn_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zturn_auto_pc_0 || ORIG_REF_NAME==zturn_auto_pc_0} -quiet] -quiet

# XDC: /home/duyliontran/xilinx/zturn-driver/zturn-driver.gen/sources_1/bd/zturn/zturn_ooc.xdc
